In [1]:
# FFNN Python
def f(w, x):
    lst = []
    for ele in zip(w,x):
        lst.append(ele[0] * ele[1])
    return lst

def ReLU(x):
    lst = []
    for i in x:
        lst.append(max(0, i))
    return lst

def softmax(x):
    e = 2.71828
    exp_i = []
    for i in x:
        exp_i.append((e ** i))
    exp_i_sum = sum(exp_i)
    probs = []
    for i in exp_i:
        probs.append(i / exp_i_sum)
    return probs

xs = [-1,2]
ws = [4,5]
ws2 = [7,8]

l1 = f(ws,xs)
act1 = ReLU(l1)
l2 = f(ws2, act1)
probabilities = softmax(l2)
probabilities

[1.804948513513993e-35, 1.0]

In [2]:
# Loss, Categorical Cross Entropy
# Python
def categorical_cross_entropy(probabilities):
    import math
    
    y = [1,0]
    
    loss = 0
    for i in range(len(y)):
        loss -= y[i] * math.log(probabilities[i])
    
    return loss

categorical_cross_entropy(probabilities)

79.99994618778256

In [29]:
# FFNN numpy
import numpy as np

def f(w,x):
    return w * x

def ReLU(x):
    return np.maximum(0, x)

def softmax(x):
    return np.e**x / np.sum(np.e**x)

xs = np.array([-1,2])
ws = np.array([4,5])
ws2 = np.array([7,8])

l1 = f(ws,xs)
act1 = ReLU(l1)
l2 = f(ws2, act1)
probabilities = softmax(l2)
probabilities

array([1.80485139e-35, 1.00000000e+00])

In [34]:
# Loss, Categorical Cross Entropy
# numpy
import numpy as np
y = np.array([1,0])
-np.log(np.sum(probabilities * y))

80.0

In [5]:
# FFNN pytorch

import torch

def f(w,x):
    return w * x

def ReLU(x):
    return torch.relu(x)

def softmax(x):
    return torch.e**x / torch.sum(torch.e**x)

xs = torch.tensor([-1,2])
ws = torch.tensor([4,5])
ws2 = torch.tensor([7,8])

l1 = f(ws,xs)
act1 = ReLU(l1)
l2 = f(ws2, act1)
logits = l2
probabilities = softmax(logits)
probabilities

tensor([1.8049e-35, 1.0000e+00])

In [6]:
# Loss, Categorical Cross Entropy
# pytorch
import torch
y = torch.tensor([1,0])
# -torch.log(torch.sum(probabilities * y))


# built in
ce_obj = torch.nn.CrossEntropyLoss()
ce_obj(logits.float(), torch.argmax(y))

tensor(80.)

In [87]:
# FFNN scipy & numpy

import scipy as sp
import numpy as np


def f(w,x):
    return w * x

def ReLU(x):
    return np.maximum(0, x)

def softmax(x):
    return sp.special.softmax(x)

xs = np.array([-1,2])
ws = np.array([4,5])
ws2 = np.array([7,8])

l1 = f(ws,xs)
act1 = ReLU(l1)
l2 = f(ws2, act1)
logits = l2
probabilities = softmax(logits)
probabilities

array([1.80485139e-35, 1.00000000e+00])

In [85]:
# Loss, Categorical Cross Entropy
# scipy & numpy

import numpy as np
from scipy.special import softmax, kl_div

y = np.array([1,0])
logits

loss = np.sum(kl_div(y, softmax(logits)))
loss

80.0