In [162]:
def f(x,w):
    return x*w

def relu(x):
    return max(0, x)

def loss(x,y):
    return (x - y)**2

x = 2
w = 7
y = 20

for i in range(10):
    l1 = f(x,w)
    a1 = relu(l1)
    loss1 = loss(a1,y)
    print(loss1)

    dloss1_da1 = 2 * (a1 - y)
    da1_dl1 = 1 if l1>=0 else 0
    dl1_dw = x
    dloss1_dw = dloss1_da1 * da1_dl1 * dl1_dw

    w = w - 0.1 * dloss1_dw

36
1.4399999999999984
0.05759999999999925
0.0023039999999998335
9.21599999999797e-05
3.686399999993731e-06
1.4745600000029495e-07
5.898239999793519e-09
2.3592959996991286e-10
9.437183990065367e-12


In [7]:
import torch
import numpy as np
from PIL import Image


im = np.array(Image.open('cat.jpg').convert('L'))
x = torch.tensor(im).flatten()
x

tensor([200, 197, 197,  ..., 108, 113, 118], dtype=torch.uint8)

In [160]:
# print(w)
w = w - 0.1 * dloss1_dw
print(w)
l1 = f(x,w)
print(l1)
a1 = relu(l1)
print(a1)
loss1 = loss(a1,y)


dloss1_da1 = 2 * (a1 - y)
da1_dl1 = 1 if l1>0 else 0
dl1_dw = x

dloss1_dw = dloss1_da1 * da1_dl1 * dl1_dw
loss1

10.000000774144
20.000001548288
20.000001548288


2.397195733789053e-12

In [10]:
# grad check
def f(x,w):
    return x*w

def relu(x):
    return max(0, x)

def loss(x,y):
    return (x - y)**2

x = 2
w = 7
y = 3

l1 = f(x,w)
a1 = relu(l1)
loss1 = loss(a1,y)

h = 0.0001

# dloss1_da1 = (loss(a1+h, y) - loss(a1, y)) / h
# drelu_dl1 = (relu(l1+h) - relu(l1)) / h
# dl1_dw = (f(x,w+h) - f(x,w)) / h

loss1




# grad check
def f(x,w):
    return x*w

def relu(x):
    return max(0, x)

def loss(x,y):
    return (x - y)**2

x = 2
w = 7
y = 3

l1 = f(x,w+h)
a1 = relu(l1)
loss1 = loss(a1,y)

h = 0.0001

# dloss1_da1 = (loss(a1+h, y) - loss(a1, y)) / h
# drelu_dl1 = (relu(l1+h) - relu(l1)) / h
# dl1_dw = (f(x,w+h) - f(x,w)) / h

(loss1 - loss1111) / h

44.00039999993055

In [3]:
# FFNN Python
import math
import numpy as np
np.random.seed(0)


class Linear:
    def __init__(self, n_in, n_out):
        self.w = np.random.randn(n_in, n_out)
        
    def forward(self, x):
        self.inputs = x
        self.output = inputs * self.w

    def backward(self, x):
        self.dw = self.inputs
        
#############################

class ActivationReLU:
    def forward(self, inputs):
        self.inputs = inputs
        return np.maximum(0, inputs)
        
    def backward(self, dvalues):
        self.drelu = np.where(self.inputs>0, 1, 0)

        
class SqErrLoss:
    def forward(self, y_hat, y):
         return (y_hat - y)**2

    def backward(self, y_hat):
        self.dy_hat = 2 * (y_hat - y)

        
x = np.array([-1,2])
y = np.array([1,0])

nn = NN(1,1)
loss = Loss()


l1 = nn.linear(x)
y_hat = nn.ReLU(l1)
sqe_loss = loss.squared_error(y_hat, y)

dl1_dw = nn.linear(x, grad_wrt='w')[1]
drelu_dx = nn.linear(x, grad_wrt='x')[1]
dsqe_loss_drelu = loss.squared_error(y_hat, y, grad_wrt='y_hat')
dsqe_loss_drelu

array([[-2.        ,  7.05620956]])

In [24]:
# Loss, Categorical Cross Entropy
# Python
def categorical_cross_entropy(probabilities):
    import math
    
    y = [1,0]
    
    loss = 0
    for i in range(len(y)):
        loss -= y[i] * math.log(probabilities[i])
    
    return loss

categorical_cross_entropy(probabilities)

6.002471659200743

In [29]:
# FFNN numpy
import numpy as np

def f(w,x):
    return w * x

def ReLU(x):
    return np.maximum(0, x)

def softmax(x):
    return np.e**x / np.sum(np.e**x)

xs = np.array([-1,2])
ws = np.array([4,5])
ws2 = np.array([7,8])

l1 = f(ws,xs)
act1 = ReLU(l1)
l2 = f(ws2, act1)
probabilities = softmax(l2)
probabilities

array([1.80485139e-35, 1.00000000e+00])

In [34]:
# Loss, Categorical Cross Entropy
# numpy
import numpy as np
y = np.array([1,0])
-np.log(np.sum(probabilities * y))

80.0

In [5]:
# FFNN pytorch

import torch

def f(w,x):
    return w * x

def ReLU(x):
    return torch.relu(x)

def softmax(x):
    return torch.e**x / torch.sum(torch.e**x)

xs = torch.tensor([-1,2])
ws = torch.tensor([4,5])
ws2 = torch.tensor([7,8])

l1 = f(ws,xs)
act1 = ReLU(l1)
l2 = f(ws2, act1)
logits = l2
probabilities = softmax(logits)
probabilities

tensor([1.8049e-35, 1.0000e+00])